CREATE DATABASE pokemonproject4;
\c pokemonproject4

DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS pokemon;

CREATE TABLE team(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE pokemon(
  id BIGSERIAL PRIMARY KEY,
  team_id INTEGER REFERENCES team(id),
  name VARCHAR(255),
  image VARCHAR(255)
);
